"""Plan a sharded ntuplization of the full Delphes production, and emit a submit file.

    pixi run python scripts/make_shards.py \
        --sample signal /ceph/jpan/gen-delphes/'*kl-*Delphes_v1'  cards/tuning/maps_v1.json \
        --sample ttbar  /ceph/jpan/gen-delphes/'*TT*Delphes_v1'   cards/tuning/maps_ttbar_v1.json \
        --out /ceph/jpan/ntuples --shard-events 150000

Sharding here is forced by MEMORY, not speed. ``DelphesEvents`` concatenates every file
it is given and holds the gen record as a cached_property, ~28 B per gen particle — about
84 GB at 1.5M events x 2000 particles, an order of magnitude over a normal batch slot.
CPU is not the constraint: the whole 300M-event campaign is ~50 core-hours after the
restricted ancestry walk.

Shards are cut at FILE granularity because that is the only correct axis: there is no
``entry_start`` anywhere in the readers, so ``--entry-stop`` is a head-only cap and two
jobs using it would read overlapping heads, never disjoint slices.

Each shard gets its OWN SEED. A shared seed replays one uniform stream across shards,
which leaves every marginal unbiased (P(tag) = eff at any stream position) but understates
the variance of aggregate yields. Seed 0 is reserved for the tuning-lens identity.
"""

from __future__ import annotations

import argparse
import fnmatch
import glob
import json
import os
import re
import subprocess

_SUB = """# HTCondor submit for the Delphes ntuplization, generated by scripts/make_shards.py
universe                = vanilla
executable              = {exe}
# NOT `should_transfer_files = NO`: that tells Condor a shared filesystem exists, which
# makes it require TARGET.FileSystemDomain == MY.FileSystemDomain — and every machine in
# this pool advertises its OWN hostname as its domain, so only the submit node ever
# matched (1 slot of 47). YES transfers just the executable; the job reads /ceph and
# writes its parquet there by absolute path, so nothing comes back through the sandbox.
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_executable     = true
transfer_output_files   = ""
requirements            = {reqs}
{proxy}
request_cpus            = 1
request_memory          = {mem}
request_disk            = 4 GB
+RequestRuntime         = {runtime}
log                     = {logdir}/$(sample).$(shard).log
output                  = {logdir}/$(sample).$(shard).out
error                   = {logdir}/$(sample).$(shard).err
arguments               = "$(sample) $(shard) $(filelist) $(maps) $(outfile) $(seed)"
queue sample, shard, filelist, maps, outfile, seed from {queue}
"""

_EXE = """#!/usr/bin/env bash
# one shard: $1=sample $2=shard $3=filelist $4=maps $5=outfile $6=seed
set -euo pipefail
cd {repo}
# The env's interpreter DIRECTLY, not `pixi run`: pixi is on the submit node's PATH but
# not on the workers', which fails every job with exit 127 six seconds in. The absolute
# path is what runners/probe_worker.sh verified is importable on the batch nodes.
PY="{repo}/.pixi/envs/{env}/bin/python"
if [ ! -x "$PY" ]; then
    echo "no interpreter at $PY (is /ceph mounted on $(hostname -f)?)" >&2
    exit 127
fi
exec "$PY" -m delphes_pipeline.ntuplizer.convert \\
    --files-from "$3" --tuning-maps "$4" --seed "$6" --shard "$2" {prune} "" "$5"
"""


_SUBTREE = re.compile(r"(delphes-tree-[0-9a-f]+)")


def _xrd_files(pattern, cache=None, refresh=False):
    """List ``root://host//path/pattern`` recursively via xrdfs (glob cannot expand a URL).

    The listing is CACHED: walking 72k files over XRootD costs minutes and the remote tree
    does not change between planning runs, so re-listing on every invocation just to
    re-cut the shards is wasted. ``refresh=True`` re-lists.
    """
    if cache and os.path.exists(cache) and not refresh:
        with open(cache) as fh:
            rows = [ln.rstrip("\n").split("\t") for ln in fh if ln.strip()]
        print(f"[shards] listing from cache {cache} ({len(rows)} files; REFRESH=1 to re-list)")
        return [(r[0], int(r[1])) for r in rows]
    m = re.match(r"^(root://[^/]+)/+(/.*)$", pattern)
    if not m:
        raise SystemExit(f"[shards] cannot parse XRootD URL: {pattern}")
    host, path = m.group(1)[len("root://"):], m.group(2)
    root = path.split("*")[0].rstrip("/") or "/"
    try:
        # -l gives the SIZE for free; that is what shards are cut on, and asking for it
        # here avoids opening 60k remote files just to learn how big they are
        out = subprocess.check_output(["xrdfs", host, "ls", "-l", "-R", root], text=True)
    except FileNotFoundError:
        raise SystemExit("[shards] xrdfs not on PATH — need the XRootD client to list dCache")
    except subprocess.CalledProcessError as e:
        raise SystemExit(f"[shards] xrdfs failed on {host}{root} (grid proxy?): {e}")
    hits = []
    for ln in out.splitlines():                      # <perms> <date> <time> <size> <path>
        parts = ln.split()
        if len(parts) < 2 or not parts[-1].endswith(".root"):
            continue
        h = parts[-1]
        if fnmatch.fnmatch(h, path + "*") or fnmatch.fnmatch(h, path):
            try:
                hits.append((f"root://{host}/{h}", int(parts[-2])))
            except ValueError:
                hits.append((f"root://{host}/{h}", 0))
    hits = sorted(hits)
    if cache:
        os.makedirs(os.path.dirname(cache) or ".", exist_ok=True)
        with open(cache, "w") as fh:
            fh.write("\n".join(f"{f}\t{n}" for f, n in hits) + "\n")
        print(f"[shards] cached listing -> {cache} ({len(hits)} files)")
    return hits


def _files(pattern, subtree=None, cache=None, refresh=False):
    """[(path, size_bytes)] — size is the shard axis, and it costs nothing to collect."""
    if pattern.startswith("root://"):
        out = _xrd_files(pattern, cache=cache, refresh=refresh)
    else:
        paths = []
        for h in sorted(glob.glob(pattern)):
            if os.path.isdir(h):
                paths += sorted(glob.glob(os.path.join(h, "**", "*.root"), recursive=True))
            elif h.endswith(".root"):
                paths.append(h)
        out = [(f, os.path.getsize(f) if os.path.exists(f) else 0) for f in paths]
    if subtree:
        rx = re.compile(subtree)
        out = [(f, n) for f, n in out if rx.search(f)]
    return out


def check_subtrees(name, files):
    """Refuse a file set spanning several production subtrees.

    The Delphes production carries more than one ``delphes-tree-<hash>`` per dataset, and
    they hold the SAME events (see download_gen_delphes.sh SUBTREE_RE). Both
    ``resolve_paths`` and this planner expand a directory with ``**/*.root``, so spanning
    two of them silently DOUBLE-COUNTS every event — an error that survives all the way to
    a wrong cross-section with nothing anywhere flagging it.
    """
    hashes = sorted({m.group(1) for f, _ in files if (m := _SUBTREE.search(f))})
    if len(hashes) > 1:
        print(f"[shards] ERROR {name}: files span {len(hashes)} production subtrees "
              f"holding the SAME events -> {', '.join(hashes)}")
        print(f"[shards]   this would double-count. Pick one with --subtree, e.g. "
              f"--subtree '{hashes[0]}'")
        return False
    if hashes:
        print(f"[shards] {name}: subtree {hashes[0]}")
    return True


def _events(path):
    """Entry count without reading any payload branch."""
    import uproot
    try:
        with uproot.open(path) as f:
            return f["Delphes"].num_entries
    except Exception:
        return None


def verify(outdir):
    """Check a finished campaign against its plan: every shard present, exactly once."""
    import awkward as ak
    plan = json.load(open(os.path.join(outdir, "_plan", "manifest.json")))["shards"]
    missing, empty, total, seen = [], [], 0, {}
    for e in plan:
        if not os.path.exists(e["out"]):
            missing.append((e["sample"], e["shard"])); continue
        a = ak.from_parquet(e["out"])
        n = len(a)
        total += n
        if n == 0:
            empty.append((e["sample"], e["shard"]))
        if "shard" in ak.fields(a):
            for sh in set(ak.to_numpy(a["shard"]).tolist()):
                seen.setdefault((e["sample"], int(sh)), []).append(e["out"])
    dup = {k: v for k, v in seen.items() if len(v) > 1}
    print(f"[verify] {len(plan) - len(missing)}/{len(plan)} shards present, {total:,} events")
    for lbl, items in (("MISSING", missing), ("EMPTY", empty)):
        if items:
            print(f"[verify] {lbl}: " + ", ".join(f"{s}.{i:04d}" for s, i in sorted(items)))
    if dup:
        print(f"[verify] DUPLICATED shard ids: {sorted(dup)}")
    ok = not (missing or dup)
    print("[verify] " + ("complete and unique" if ok else "INCOMPLETE — do not merge"))
    return 0 if ok else 1


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--verify", metavar="OUTDIR",
                    help="audit a finished campaign against its manifest and exit")
    ap.add_argument("--sample", nargs="+", action="append",
                    metavar="NAME GLOB MAPS [SUBTREE]",
                    help="repeatable: a sample, its files, its OWN maps, and optionally the "
                         "production subtree to keep. The subtree is PER SAMPLE: the full "
                         "production is delphes-tree-61fd1c12 for the signal but "
                         "delphes-tree-2ff38f65 for ttbar/DY, and a bare hash is not a "
                         "portable key (6d2d1cb0 is the signal TEST and also the ttbar v0 "
                         "subtree), so always pair it with '_Delphes_v1/'.")
    ap.add_argument("--out", help="output directory for the parquet shards "
                                  "(not needed with --verify)")
    ap.add_argument("--shard-files", type=int, default=400,
                    help="fallback cap on files per shard, used when sizes are unavailable "
                         "and as a hard ceiling otherwise — without it a listing that "
                         "reports no sizes would put the entire sample in one job")
    ap.add_argument("--shard-gb", type=float, default=12.0,
                    help="target INPUT GB per shard. Memory sets this, not speed: the "
                         "reader concatenates a shard and caches the gen record at ~28 B "
                         "per gen particle, so a shard has to fit the slot.")
    ap.add_argument("--shard-events", type=int, default=None,
                    help="target EVENTS per shard instead; requires --count-events, which "
                         "opens every file for its header")
    ap.add_argument("--env", default="nsbi-env-gpu")
    ap.add_argument("--memory", default="8 GB")
    ap.add_argument("--runtime", type=int, default=10800)
    ap.add_argument("--refresh", action="store_true",
                    help="re-list the remote tree instead of reusing the cached listing")
    ap.add_argument("--requirements",
                    default='regexp("etp\\.kit\\.edu$", TARGET.Machine)',
                    help="slot requirement. Default pins to the ETP machines, which a "
                         "probe confirmed can see /ceph, import the pixi env and read "
                         "dCache; the NEMO nodes in this pool were not verified and a job "
                         "landing there would fail on a missing environment.")
    ap.add_argument("--proxy", default=None,
                    help="grid proxy for the workers, needed only when reading root:// . "
                         "voms-proxy-init writes /tmp/x509up_u$(id -u), which worker nodes "
                         "cannot see — copy it somewhere shared and pass that path.")
    ap.add_argument("--no-prune", action="store_true",
                    help="write the FULL gen record (~9 TB at 300M events instead of ~0.4)")
    ap.add_argument("--subtree", default=None,
                    help="fallback subtree regex for samples that give none of their own")
    ap.add_argument("--count-events", action="store_true",
                    help="open each file for its entry count (accurate but slower)")
    args = ap.parse_args(argv)
    if args.verify:
        return verify(os.path.abspath(args.verify))
    # argparse cannot express "required unless --verify", so enforce it here
    if not args.sample or not args.out:
        ap.error("--sample and --out are required unless --verify is given")

    repo = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
    outdir = os.path.abspath(args.out)
    plandir, logdir = os.path.join(outdir, "_plan"), os.path.join(outdir, "_log")
    for d in (outdir, plandir, logdir):
        os.makedirs(d, exist_ok=True)

    rows, manifest, seed = [], [], 1        # seed 0 stays reserved for the tuning lens
    for spec in args.sample:
        if len(spec) not in (3, 4):
            raise SystemExit(f"[shards] --sample takes NAME GLOB MAPS [SUBTREE], got {spec}")
        name, pattern, maps = spec[:3]
        sub = spec[3] if len(spec) == 4 else args.subtree
        files = _files(pattern, subtree=sub, refresh=args.refresh,
                       cache=os.path.join(plandir, f"listing.{name}.tsv"))
        if files and not check_subtrees(name, files):
            raise SystemExit(2)
        if not files:
            print(f"[shards] WARNING {name}: no files matched {pattern}")
            continue
        if not os.path.exists(maps):
            print(f"[shards] WARNING {name}: maps {maps} not found — derive them first")
        by_events = args.count_events and args.shard_events
        counts = [_events(f) for f, _ in files] if args.count_events else [None] * len(files)
        target = args.shard_events if by_events else args.shard_gb * 1e9
        shards, cur, acc = [], [], 0.0
        for (f, size), c in zip(files, counts):
            cur.append(f)
            acc += (c or 0) if by_events else size
            if acc >= target or len(cur) >= args.shard_files:
                shards.append(cur); cur, acc = [], 0.0
        if cur:
            shards.append(cur)
        tot_b = sum(n for _, n in files)
        tot_e = sum(c for c in counts if c) if args.count_events else None
        print(f"[shards] {name}: {len(files)} files, {tot_b/1e12:.2f} TB"
              + (f", {tot_e:,} events" if tot_e else "")
              + f" -> {len(shards)} shards"
              + (f" (~{tot_b/1e9/max(len(shards),1):.1f} GB each)" if not by_events else ""))
        if not by_events and tot_b == 0:
            print(f"[shards] WARNING {name}: listing reported no file sizes — shards fell "
                  f"back to {args.shard_files} files each; check they fit the slot")
        for i, chunk in enumerate(shards):
            fl = os.path.join(plandir, f"{name}.{i:04d}.txt")
            with open(fl, "w") as fh:
                fh.write("\n".join(chunk) + "\n")
            outfile = os.path.join(outdir, f"{name}.{i:04d}.parquet")
            rows.append(f"{name}, {i}, {fl}, {os.path.abspath(maps)}, {outfile}, {seed}")
            manifest.append({"sample": name, "shard": i, "seed": seed, "maps": maps,
                             "subtree": sub, "files": chunk, "out": outfile})
            seed += 1

    queue = os.path.join(plandir, "shards.txt")
    with open(queue, "w") as fh:
        fh.write("\n".join(rows) + "\n")
    exe = os.path.join(plandir, "run_shard.sh")
    with open(exe, "w") as fh:
        fh.write(_EXE.format(repo=repo, env=args.env,
                             prune="" if args.no_prune else "--prune-genpart"))
    os.chmod(exe, 0o755)
    remote = any(f.startswith("root://") for e in manifest for f in e["files"])
    if remote and not args.proxy:
        print("[shards] WARNING: inputs are root:// but no --proxy given. Worker nodes "
              "cannot read /tmp/x509up_u$(id -u) from the login node; the jobs will fail "
              "to authenticate to dCache.")
    proxy = (f"x509userproxy          = {os.path.abspath(args.proxy)}\n"
             "use_x509userproxy       = true" if args.proxy else "")
    sub = os.path.join(plandir, "ntuplize.sub")
    with open(sub, "w") as fh:
        fh.write(_SUB.format(exe=exe, logdir=logdir, queue=queue, proxy=proxy,
                             reqs=args.requirements, mem=args.memory,
                             runtime=args.runtime))
    with open(os.path.join(plandir, "manifest.json"), "w") as fh:
        json.dump({"shards": manifest, "prune_genpart": not args.no_prune}, fh, indent=2)

    try:
        sha = subprocess.check_output(["git", "-C", repo, "rev-parse", "--short", "HEAD"],
                                      text=True).strip()
    except Exception:
        sha = "unknown"
    print(f"\n[shards] {len(rows)} shards planned at {repo} ({sha})")
    print(f"[shards] manifest {plandir}/manifest.json")
    print(f"[shards] submit with:  condor_submit {sub}")
    print(f"[shards] verify with:  pixi run python scripts/make_shards.py --verify {outdir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
