"""Plan a sharded ntuplization of the full Delphes production, and emit a submit file.

    pixi run python scripts/make_shards.py \
        --sample signal /ceph/jpan/gen-delphes/'*kl-*Delphes_v1'  cards/tuning/maps_v1.json \
        --sample ttbar  /ceph/jpan/gen-delphes/'*TT*Delphes_v1'   cards/tuning/maps_ttbar_v1.json \
        --out /ceph/jpan/ntuples --shard-events 150000

Sharding here is forced by MEMORY, not speed. ``DelphesEvents`` concatenates every file
it is given and holds the gen record as a cached_property, ~28 B per gen particle — about
84 GB at 1.5M events x 2000 particles, an order of magnitude over a normal batch slot.
CPU is not the constraint: the whole 300M-event campaign is ~50 core-hours after the
restricted ancestry walk.

Shards are cut at FILE granularity because that is the only correct axis: there is no
``entry_start`` anywhere in the readers, so ``--entry-stop`` is a head-only cap and two
jobs using it would read overlapping heads, never disjoint slices.

Each shard gets its OWN SEED. A shared seed replays one uniform stream across shards,
which leaves every marginal unbiased (P(tag) = eff at any stream position) but understates
the variance of aggregate yields. Seed 0 is reserved for the tuning-lens identity.
"""

from __future__ import annotations

import argparse
import fnmatch
import glob
import json
import os
import re
import subprocess

_SUB = """# HTCondor submit for the Delphes ntuplization, generated by scripts/make_shards.py
universe                = vanilla
executable              = {exe}
should_transfer_files   = NO
request_cpus            = 1
request_memory          = {mem}
request_disk            = 4 GB
+RequestRuntime         = {runtime}
log                     = {logdir}/$(sample).$(shard).log
output                  = {logdir}/$(sample).$(shard).out
error                   = {logdir}/$(sample).$(shard).err
arguments               = "$(sample) $(shard) $(filelist) $(maps) $(outfile) $(seed)"
queue sample, shard, filelist, maps, outfile, seed from {queue}
"""

_EXE = """#!/usr/bin/env bash
# one shard: $1=sample $2=shard $3=filelist $4=maps $5=outfile $6=seed
set -euo pipefail
cd {repo}
exec pixi run -e {env} python -m delphes_pipeline.ntuplizer.convert \\
    --files-from "$3" --tuning-maps "$4" --seed "$6" --shard "$2" {prune} "" "$5"
"""


_SUBTREE = re.compile(r"(delphes-tree-[0-9a-f]+)")


def _xrd_files(pattern):
    """List ``root://host//path/pattern`` recursively via xrdfs (glob cannot expand a URL)."""
    m = re.match(r"^(root://[^/]+)/+(/.*)$", pattern)
    if not m:
        raise SystemExit(f"[shards] cannot parse XRootD URL: {pattern}")
    host, path = m.group(1)[len("root://"):], m.group(2)
    root = path.split("*")[0].rstrip("/") or "/"
    try:
        out = subprocess.check_output(["xrdfs", host, "ls", "-R", root], text=True)
    except FileNotFoundError:
        raise SystemExit("[shards] xrdfs not on PATH — need the XRootD client to list dCache")
    except subprocess.CalledProcessError as e:
        raise SystemExit(f"[shards] xrdfs failed on {host}{root} (grid proxy?): {e}")
    hits = [ln.strip() for ln in out.splitlines() if ln.strip().endswith(".root")]
    return sorted(f"root://{host}/{h}" for h in hits if fnmatch.fnmatch(h, path + "*")
                  or fnmatch.fnmatch(h, path))


def _files(pattern, subtree=None):
    if pattern.startswith("root://"):
        out = _xrd_files(pattern)
    else:
        out = []
        for h in sorted(glob.glob(pattern)):
            if os.path.isdir(h):
                out += sorted(glob.glob(os.path.join(h, "**", "*.root"), recursive=True))
            elif h.endswith(".root"):
                out.append(h)
    if subtree:
        rx = re.compile(subtree)
        out = [f for f in out if rx.search(f)]
    return out


def check_subtrees(name, files):
    """Refuse a file set spanning several production subtrees.

    The Delphes production carries more than one ``delphes-tree-<hash>`` per dataset, and
    they hold the SAME events (see download_gen_delphes.sh SUBTREE_RE). Both
    ``resolve_paths`` and this planner expand a directory with ``**/*.root``, so spanning
    two of them silently DOUBLE-COUNTS every event — an error that survives all the way to
    a wrong cross-section with nothing anywhere flagging it.
    """
    hashes = sorted({m.group(1) for f in files if (m := _SUBTREE.search(f))})
    if len(hashes) > 1:
        print(f"[shards] ERROR {name}: files span {len(hashes)} production subtrees "
              f"holding the SAME events -> {', '.join(hashes)}")
        print(f"[shards]   this would double-count. Pick one with --subtree, e.g. "
              f"--subtree '{hashes[0]}'")
        return False
    if hashes:
        print(f"[shards] {name}: subtree {hashes[0]}")
    return True


def _events(path):
    """Entry count without reading any payload branch."""
    import uproot
    try:
        with uproot.open(path) as f:
            return f["Delphes"].num_entries
    except Exception:
        return None


def verify(outdir):
    """Check a finished campaign against its plan: every shard present, exactly once."""
    import awkward as ak
    plan = json.load(open(os.path.join(outdir, "_plan", "manifest.json")))["shards"]
    missing, empty, total, seen = [], [], 0, {}
    for e in plan:
        if not os.path.exists(e["out"]):
            missing.append((e["sample"], e["shard"])); continue
        a = ak.from_parquet(e["out"])
        n = len(a)
        total += n
        if n == 0:
            empty.append((e["sample"], e["shard"]))
        if "shard" in ak.fields(a):
            for sh in set(ak.to_numpy(a["shard"]).tolist()):
                seen.setdefault((e["sample"], int(sh)), []).append(e["out"])
    dup = {k: v for k, v in seen.items() if len(v) > 1}
    print(f"[verify] {len(plan) - len(missing)}/{len(plan)} shards present, {total:,} events")
    for lbl, items in (("MISSING", missing), ("EMPTY", empty)):
        if items:
            print(f"[verify] {lbl}: " + ", ".join(f"{s}.{i:04d}" for s, i in sorted(items)))
    if dup:
        print(f"[verify] DUPLICATED shard ids: {sorted(dup)}")
    ok = not (missing or dup)
    print("[verify] " + ("complete and unique" if ok else "INCOMPLETE — do not merge"))
    return 0 if ok else 1


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--verify", metavar="OUTDIR",
                    help="audit a finished campaign against its manifest and exit")
    ap.add_argument("--sample", nargs=3, action="append", metavar=("NAME", "GLOB", "MAPS"),
                    help="repeatable: a sample, its files, and ITS OWN maps")
    ap.add_argument("--out", required=True, help="output directory for the parquet shards")
    ap.add_argument("--shard-events", type=int, default=150000,
                    help="target events per shard; memory, not speed, sets this")
    ap.add_argument("--env", default="nsbi-env-gpu")
    ap.add_argument("--memory", default="8 GB")
    ap.add_argument("--runtime", type=int, default=10800)
    ap.add_argument("--no-prune", action="store_true",
                    help="write the FULL gen record (~9 TB at 300M events instead of ~0.4)")
    ap.add_argument("--subtree", default=None,
                    help="regex selecting ONE production subtree, e.g. "
                         "'delphes-tree-2ff38f65'. The production holds several per "
                         "dataset with the same events; spanning them double-counts.")
    ap.add_argument("--count-events", action="store_true",
                    help="open each file for its entry count (accurate but slower)")
    args = ap.parse_args(argv)
    if args.verify:
        return verify(os.path.abspath(args.verify))
    if not args.sample:
        ap.error("--sample is required unless --verify is given")

    repo = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
    outdir = os.path.abspath(args.out)
    plandir, logdir = os.path.join(outdir, "_plan"), os.path.join(outdir, "_log")
    for d in (outdir, plandir, logdir):
        os.makedirs(d, exist_ok=True)

    rows, manifest, seed = [], [], 1        # seed 0 stays reserved for the tuning lens
    for name, pattern, maps in args.sample:
        files = _files(pattern, subtree=args.subtree)
        if files and not check_subtrees(name, files):
            raise SystemExit(2)
        if not files:
            print(f"[shards] WARNING {name}: no files matched {pattern}")
            continue
        if not os.path.exists(maps):
            print(f"[shards] WARNING {name}: maps {maps} not found — derive them first")
        counts = [_events(f) if args.count_events else None for f in files]
        shards, cur, n = [], [], 0
        for f, c in zip(files, counts):
            cur.append(f)
            n += c if c else args.shard_events // max(len(files) // 8, 1)
            if n >= args.shard_events:
                shards.append(cur); cur, n = [], 0
        if cur:
            shards.append(cur)
        print(f"[shards] {name}: {len(files)} files -> {len(shards)} shards"
              + (f", {sum(c for c in counts if c):,} events" if args.count_events else ""))
        for i, chunk in enumerate(shards):
            fl = os.path.join(plandir, f"{name}.{i:04d}.txt")
            with open(fl, "w") as fh:
                fh.write("\n".join(chunk) + "\n")
            outfile = os.path.join(outdir, f"{name}.{i:04d}.parquet")
            rows.append(f"{name}, {i}, {fl}, {os.path.abspath(maps)}, {outfile}, {seed}")
            manifest.append({"sample": name, "shard": i, "seed": seed, "maps": maps,
                             "files": chunk, "out": outfile})
            seed += 1

    queue = os.path.join(plandir, "shards.txt")
    with open(queue, "w") as fh:
        fh.write("\n".join(rows) + "\n")
    exe = os.path.join(plandir, "run_shard.sh")
    with open(exe, "w") as fh:
        fh.write(_EXE.format(repo=repo, env=args.env,
                             prune="" if args.no_prune else "--prune-genpart"))
    os.chmod(exe, 0o755)
    sub = os.path.join(plandir, "ntuplize.sub")
    with open(sub, "w") as fh:
        fh.write(_SUB.format(exe=exe, logdir=logdir, queue=queue,
                             mem=args.memory, runtime=args.runtime))
    with open(os.path.join(plandir, "manifest.json"), "w") as fh:
        json.dump({"shards": manifest, "prune_genpart": not args.no_prune}, fh, indent=2)

    try:
        sha = subprocess.check_output(["git", "-C", repo, "rev-parse", "--short", "HEAD"],
                                      text=True).strip()
    except Exception:
        sha = "unknown"
    print(f"\n[shards] {len(rows)} shards planned at {repo} ({sha})")
    print(f"[shards] manifest {plandir}/manifest.json")
    print(f"[shards] submit with:  condor_submit {sub}")
    print(f"[shards] verify with:  pixi run python scripts/make_shards.py --verify {outdir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
